accounts/urls.py
from django.urls import path, reverse

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/create/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('profile/edit_profile/<int:pk>/', views.edit_profile, name='edit_profile'),
    path('profile/subscribe/<int:pk>/', views.toggle_subscribe, name='subscribe'),
    path('profile/unsubscribe/<int:pk>/', views.toggle_subscribe, name='unsubscribe'),
]

api/urls.py
from django.urls import path

from api import views

app_name = 'api'


urlpatterns = [
    path('movies/genres/', views.GenresListAPIView.as_view(), name='genres_list'),
    path('movies/genres/<int:pk>/', views.GenresDetailAPIView.as_view(), name='genres_detail'),
    path('movies/movies/', views.MoviesListAPIView.as_view(), name='movies_list'),
    path('movies/movies/<int:pk>/', views.MovieDetailAPIView.as_view(), name='movies_detail'),
    #
    # path('posts/posts', views.PostListAPIView.as_view(), name='post_list'),
    # path('posts/posts/<int:pk>/', views.PostDetailAPIView.as_view(), name='post_detail'),
    path('posts/category', views.CategoryListAPIView.as_view(), name='category_list'),
    path('posts/category/<int:pk>/', views.CategoryDetailAPIView.as_view(), name='category_detail'),
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('posts/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post/<int:post_pk>/comment/create/', views.add_post_comment, name='post_comment_create'),
    path('post/create/', views.add_post, name='add_post'),
    path('post/from/', views.from_post, name='from_post'),
    path('post/search/', views.PostSearchView.as_view(), name='search_posts'),
    path('post/toggle_edit/<slug:slug>', views.edit_post, name='toggle_edit_post'),
    path('post/edit/<slug:slug>/', views.form_edit_post, name='edit_post'),
    path('post/post_like/<int:pk>/', views.toggle_post_like, name='post_like_toggle'),
    path('post/post_dislike/<int:pk>/', views.toggle_post_dislike, name='post_dislike_toggle'),
    path('post/<int:pk>/comment_like/<int:comment_pk>/', views.toggle_comment_like, name='comment_like_toggle'),
    path('post/<int:pk>/comment_dislike/<int:comment_pk>/', views.toggle_comment_dislike, name='comment_dislike_toggle')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include("blog.urls", namespace='blog')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('rick-and-morty/', include("rick_and_morty.urls", namespace='rick_and_morty')),
    path('weather/', include("weather.urls", namespace='weather')),
    path('api/1.0/', include("api.urls", namespace='api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from movies import views

app_name = 'movies'

urlpatterns = [
    path('', views.MoviesConvertView.as_view(), name='convert'),
    path('update', views.movies_update, name='update'),
    path('delete/', views.MoviesDeleteView.as_view(), name='delete'),
]

weather/urls.py
from django.urls import path

from .views import widget, CatalogView, AddView, delete, forecast

app_name = 'weather'

urlpatterns = [
    path('widget/', widget, name='widget'),
    path('forecast/', forecast, name='forecast'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('add/', AddView.as_view(), name='add'),
    path('delete/<slug:slug>', delete, name='delete')
    # path('add/toggle/', toggle_add_city, name="toggle_add"),
]

templates/base/nav/_footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top fixed-bottom">

  <div class="container d-flex">
    <div class="col-md-4 justify-content-start align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="text-muted">© 2021 Company, Inc</span>
    </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex ">
        <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-twitter fa-xl"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-instagram fa-xl"></i></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-facebook fa-xl"></i></a></li>
      </ul>
  </div>

</footer>

templates/base/nav/_header.html
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'blog:home' %}" class="nav-link px-2 text-secondary">Home</a></li>
        <li><a href="{% url 'weather:catalog'%}" class="nav-link px-2 text-white">Weather</a></li>
        <li><a href="{% url 'rick_and_morty:episodes_list' %}" class="nav-link px-2 text-white">Rick And Morty</a></li>
        <li><a href="{% url 'movies:convert' %}" class="nav-link px-2 text-white">Movies</a></li>
        <li><a href="#" class="nav-link px-2 text-white">About</a></li>
      </ul>

      <form action="{% url 'blog:search_posts' %}" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search" name="search">
      </form>

      <div class="text-end">
        {% if not request.user.is_authenticated %}
          <a class="btn btn-outline-light me-2" href="{% url 'accounts:login' %}">Login</a>
          <a class="btn btn-outline-light me-2" href="{% url 'accounts:register' %}">Sign Up</a>
        {% else %}
            <a class="btn btn-outline-light me-2"  href="{% url 'accounts:profile' pk=request.user.pk %} " >
                {{ request.user }}
            </a>
          <a class="btn btn-outline-light me-2" href="{% url 'accounts:logout' %}">Logout</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>

templates/base/nav/_sidebar.html
{% if request.resolver_match.app_name == 'blog' %}
<div class="flex-shrink-0 mt-2 ms-2 bg-white col-2">
  <form action="" method="get">
    <h2 class="grid-title"><i class="fa fa-filter"></i> Filters</h2>
    <hr>
    <h4>By users</h4>
    <label for="user">User</label>
    <select class="form-select" name="user" id="user">
      <option value="" selected>Select user</option>
      {% for user in users %}
        <option value="{{ user.username }}">{{ user.username }}</option>
      {% endfor %}
    </select>
    <h4>By category:</h4>
    {% for category in categories %}
      <div class="form-check">
        <label for="category_{{ category.id }}" class="form-check-label">
          {{ category.name }}
        </label>
        <input class="form-check-input"
               id="category_{{ category.id }}"
               type="checkbox" name="categories"
               value="{{ category.name }}">
      </div>
    {% endfor %}
    <div class="padding"></div>
    <h4>By date:</h4>
    <label for="date_end">From</label>
    <input type="date" class="form-control" name="date_end" id="date_end">
    <button type="submit" class="btn btn-info mt-3">Search</button>
  </form>
</div>
{% elif request.resolver_match.app_name == 'movies' %}
<div class="flex-shrink-0 mt-2 ms-2 bg-white col-2">
  <form action="" method="get">
    <h2 class="grid-title"><i class="fa fa-filter"></i> Filters</h2>
    <hr>
    <h4>By certification</h4>
    <label for="certification">Certification</label>
    <select class="form-select" name="certification" id="certification">
      <option value="" selected>Select certification</option>
      {% for certification in certifications %}
        <option value="{{ certification.name }}">{{ certification.name }}</option>
      {% endfor %}
    </select>
    <h4>By genre:</h4>
    {% for genre in genres %}
      <div class="form-check">
        <label for="genre_{{ genre.id }}" class="form-check-label">
          {{ genre.name }}
        </label>
        <input class="form-check-input"
               id="genre_{{ genre.id }}"
               type="checkbox" name="genre"
               value="{{ genre.name }}">
      </div>
    {% endfor %}
    <div class="padding"></div>
    <h4>By year:</h4>
    <label for="year">From</label>
    <input type="number" class="form-control" name="year" id="year" min="1915" max="2023">
    <button type="submit" class="btn btn-info mt-3">Search</button>
  </form>
</div>
{% endif %}