accounts/urls.py
from django.urls import path, reverse

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/create/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('profile/edit_profile/<int:pk>/', views.edit_profile, name='edit_profile'),
    path('profile/subscribe/<int:pk>/', views.toggle_subscribe, name='subscribe'),
    path('profile/unsubscribe/<int:pk>/', views.toggle_subscribe, name='unsubscribe'),
]

api/urls.py
from django.urls import path

from api import views

app_name = 'api'


urlpatterns = [
    path('movies/genres/', views.GenresListAPIView.as_view(), name='genres_list'),
    path('movies/genres/<int:pk>/', views.GenresDetailAPIView.as_view(), name='genres_detail'),
    path('movies/movies/', views.MoviesListAPIView.as_view(), name='movies_list'),
    path('movies/movies/<int:pk>/', views.MovieDetailAPIView.as_view(), name='movies_detail'),
    #
    # path('posts/posts', views.PostListAPIView.as_view(), name='post_list'),
    # path('posts/posts/<int:pk>/', views.PostDetailAPIView.as_view(), name='post_detail'),
    path('posts/category', views.CategoryListAPIView.as_view(), name='category_list'),
    path('posts/category/<int:pk>/', views.CategoryDetailAPIView.as_view(), name='category_detail'),
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('posts/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post/<int:post_pk>/comment/create/', views.add_post_comment, name='post_comment_create'),
    path('post/create/', views.add_post, name='add_post'),
    path('post/from/', views.from_post, name='from_post'),
    path('post/search/', views.PostSearchView.as_view(), name='search_posts'),
    path('post/toggle_edit/<slug:slug>', views.edit_post, name='toggle_edit_post'),
    path('post/edit/<slug:slug>/', views.form_edit_post, name='edit_post'),
    path('post/post_like/<int:pk>/', views.toggle_post_like, name='post_like_toggle'),
    path('post/post_dislike/<int:pk>/', views.toggle_post_dislike, name='post_dislike_toggle'),
    path('post/<int:pk>/comment_like/<int:comment_pk>/', views.toggle_comment_like, name='comment_like_toggle'),
    path('post/<int:pk>/comment_dislike/<int:comment_pk>/', views.toggle_comment_dislike, name='comment_dislike_toggle')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include("blog.urls", namespace='blog')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('rick-and-morty/', include("rick_and_morty.urls", namespace='rick_and_morty')),
    path('weather/', include("weather.urls", namespace='weather')),
    path('api/1.0/', include("api.urls", namespace='api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import hashlib

from django.contrib.auth.models import AbstractUser
from django.db import models

from accounts.managers import CustomUserManager
from accounts.validators import validate_username, validate_name, validate_birth_date


class CustomUser(AbstractUser):
    username = models.CharField(max_length=30, unique=True, validators=[validate_username])
    email = models.EmailField(unique=True, max_length=255)
    first_name = models.CharField(max_length=50, validators=[validate_name])
    last_name = models.CharField(max_length=50, validators=[validate_name])

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = CustomUserManager()

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.first_name = self.first_name.capitalize()
        self.last_name = self.last_name.capitalize()
        self.username = self.username.lower()
        super().save(*args, **kwargs)


class Profile(models.Model):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    user = models.OneToOneField(CustomUser,
                                on_delete=models.CASCADE,
                                related_name='profile')
    avatar = models.URLField(max_length=255, blank=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    date_of_birth = models.DateField()
    bio = models.TextField()
    info = models.CharField(max_length=255)

    objects = models.Manager()

    def __str__(self):
        return f'Profile\'s of user {self.user.username}'

    def create_avatar(self):
        md5_hash = hashlib.md5(self.user.email.lower().encode('utf-8')).hexdigest()
        gravatar_url = f'https://www.gravatar.com/avatar/{md5_hash}?d=identicon&s={200}'
        self.avatar = gravatar_url

    def subscribe(self, user) -> bool:
        return ProfileSubscription.objects.filter(profile=self, user=user).exists()

    def unsubscribe(self, user):
        ProfileSubscription.objects.filter(user=user, profile=self).exists()

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
        if not self.avatar:
            self.create_avatar()
        super().save(*args, **kwargs)


class ProfileSubscription(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='subscription')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='subscription')
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'profile')

    def __str__(self):
        return f'{self.user} - {self.profile}'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from accounts.models import Profile
from accounts.validators import validate_birth_date
from blog.validators import validate_file_size

User = get_user_model()


class DateInputCustom(forms.DateInput):
    input_type = 'date'


class DefaultProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget = forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
                }
            )

    class Meta:
        model = Profile
        fields = ["gender", "date_of_birth"]


class EditProfileForm(forms.ModelForm):
    avatar = forms.ImageField(validators=[
        validate_file_size,
        FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
        required=False
    )

    class Meta:
        model = Profile
        fields = ["bio", "info"]

    bio = forms.CharField(required=False)
    info = forms.CharField(required=False)


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('gender', 'date_of_birth', 'avatar', 'bio', 'info')

        labels = {
            'date_of_birth': 'Date of your Birth',
            'avatar': 'Avatar URL'
        }

        placeholders = {
            'avatar': 'Left empty to use gravatar',
            'bio': 'Write a short biography',
            'info': 'Enter some additional information'
        }

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'placeholder': self.Meta.placeholders.get(field_name)})
        self.fields['date_of_birth'].widget = DateInputCustom()

    def clean_date_of_birth(self):
        data = self.cleaned_data['date_of_birth']
        try:
            validate_birth_date(data)
        except ValidationError as exception:
            self.add_error('date_of_birth', str(exception))
        return data

accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView

from accounts.forms import DefaultProfileForm, EditProfileForm, RegisterForm, ProfileForm
from accounts.models import Profile, ProfileSubscription
from blog.models import Post


User = get_user_model()


class UserLoginView(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('blog:home')

    def get_success_url(self):
        return self.success_url


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')


class RegisterView(FormView):
    template_name = 'accounts/registration.html'
    form_class = RegisterForm
    success_url = reverse_lazy('blog:home')


class ProfileCreateView(FormView):
    template_name = 'accounts/profile/profile_create.html'
    form_class = ProfileForm
    success_url = reverse_lazy('blog:home')

    def form_valid(self, form):
        profile = form.save(commit=False)
        profile.user = self.request.user
        profile.save()
        return super().form_valid(form)


class ProfileView(View):
    def get(self, request, pk):
        user_profile = get_object_or_404(Profile, user=pk)
        user_posts = Post.objects.filter(author=pk)
        context = {
            'profile': user_profile,
            'user_posts': user_posts,
        }
        return render(request, 'accounts/profile/profile.html', context)


@login_required
def edit_profile(request, pk):
    profile = get_object_or_404(Profile, pk=pk)

    if request.user != profile.user:
        raise PermissionDenied("You are not a profile owner")

    if request.method == "POST":
        form = EditProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', pk=pk)
    else:
        form = EditProfileForm(instance=profile)

    return render(request, 'accounts/profile/edit_profile.html', {'form': form, 'profile': profile})


@login_required
def toggle_subscribe(request, pk):
    profile_user = get_object_or_404(Profile, user=pk)
    if profile_user.user == request.user:
        return redirect('accounts:profile', pk=pk)
    profile_subscription, created = ProfileSubscription.objects.get_or_create(
        user=request.user,
        profile=profile_user,
    )
    if not created:
        profile_subscription.delete()

    return redirect('accounts:profile', pk=pk)

templates/accounts/profile/edit_profile.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}


{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-info">Save</button>
    </form>
{% endblock %}

templates/accounts/profile/profile.html
{% extends "base/_base.html" %}
{% load accounts_filters %}


{% block content %}

    <section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
              <img src="{{ profile.avatar }}"
                alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                style="width: 150px; z-index: 1">
                {% if request.user == profile.user %}
              <a href="{% url "accounts:edit_profile" pk=profile.user.pk %}" type="button" class="btn btn-outline-dark" data-mdb-ripple-color="dark"
                style="z-index: 1;">
                Edit profile
              </a>
                {% endif %}
            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h5>{{ profile.user.username }}</h5>
              <p>{{ profile.get_gender_display }}</p>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
              {% if request.user != profile.user %}
                {% if profile|subscribe:request.user %}
                    <a href="{% url 'accounts:unsubscribe' pk=profile.user.pk %}" type="submit" class="btn btn-outline-dark" data-mdb-ripple-color="dark"
                style="z-index: 1;">Unsubscribe</a>
            {% else %}
                     <a href="{% url 'accounts:subscribe' pk=profile.user.pk %}" class="btn btn-outline-dark" data-mdb-ripple-color="dark"
                style="z-index: 1;">Subscribe</a>
            {% endif %}
        {% endif %}
            <div class="d-flex justify-content-end text-center py-1">
              <div>
                <p class="mb-1 h5">{{ user_posts.all.count }}</p>
                <p class="small text-muted mb-0">Posts</p>
              </div>
              <div class="px-3">
                <p class="mb-1 h5">{{ profile.subscription.count }}</p>
                <p class="small text-muted mb-0">Followers</p>
              </div>
              <div>
                <p class="mb-1 h5">{{ profile.user.subscription.count }}</p>
                <p class="small text-muted mb-0">Following</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4" style="background-color: #f8f9fa;">
                <strong>birth</strong>
                <p class="font-italic mb-1">{{ profile.date_of_birth }}</p>
                 <strong>bio</strong>
                <p class="font-italic mb-1">{{ profile.bio }}</p>
                 <strong>info</strong>
                  <p class="font-italic mb-1">{{ profile.info }}</p>
              </div>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
              <p class="lead fw-normal mb-0">Recent post</p>
              <p class="mb-0"><a href="{% url 'blog:home' %}" class="text-muted">Show all</a></p>
            </div>
              <div class="row g-2">
                  {% for post in user_posts|slice:":2" %}
                      <div class="col mb-2">
                          <a href="{% url 'blog:post_detail' slug=post.slug %}">
                        <img src="{{ post.image.url }}"
                          alt="Image" class="w-100 rounded-3">
                              </a>
                      </div>
                  {% endfor %}
              <div class="row g-2">
                  {% for post in user_posts|slice:"2:4" %}
                      <div class="col mb-2">
                          <a href="{% url 'blog:post_detail' slug=post.slug %}">
                        <img src="{{ post.image.url }}"
                          alt="Image" class="w-100 rounded-3">
                              </a>
                      </div>
                  {% endfor %}
              </div>
          </div>
         </div>
        </div>
        </div>
    </div>
    </div>

</section>

{% endblock %}

templates/accounts/profile/profile_create.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}


{% block content %}
    <div class="d-flex justify-content-center">
      <div>
        <h1 class="mb-5">Create profile for {{ request.user.get_full_name }} </h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
        <button type="submit" class="btn btn-info">Create</button>
        </form>
      </div>
    </div>
{% endblock %}