accounts/urls.py
from django.urls import path, reverse

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/create/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('profile/edit_profile/<int:pk>/', views.edit_profile, name='edit_profile'),
    path('profile/subscribe/<int:pk>/', views.toggle_subscribe, name='subscribe'),
    path('profile/unsubscribe/<int:pk>/', views.toggle_subscribe, name='unsubscribe'),
]

api/urls.py
from django.urls import path

from api import views

app_name = 'api'


urlpatterns = [
    path('movies/genres/', views.GenresListAPIView.as_view(), name='genres_list'),
    path('movies/genres/<int:pk>/', views.GenresDetailAPIView.as_view(), name='genres_detail'),
    path('movies/movies/', views.MoviesListAPIView.as_view(), name='movies_list'),
    path('movies/movies/<int:pk>/', views.MovieDetailAPIView.as_view(), name='movies_detail'),
    #
    # path('posts/posts', views.PostListAPIView.as_view(), name='post_list'),
    # path('posts/posts/<int:pk>/', views.PostDetailAPIView.as_view(), name='post_detail'),
    path('posts/category', views.CategoryListAPIView.as_view(), name='category_list'),
    path('posts/category/<int:pk>/', views.CategoryDetailAPIView.as_view(), name='category_detail'),
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('posts/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post/<int:post_pk>/comment/create/', views.add_post_comment, name='post_comment_create'),
    path('post/create/', views.add_post, name='add_post'),
    path('post/from/', views.from_post, name='from_post'),
    path('post/search/', views.PostSearchView.as_view(), name='search_posts'),
    path('post/toggle_edit/<slug:slug>', views.edit_post, name='toggle_edit_post'),
    path('post/edit/<slug:slug>/', views.form_edit_post, name='edit_post'),
    path('post/post_like/<int:pk>/', views.toggle_post_like, name='post_like_toggle'),
    path('post/post_dislike/<int:pk>/', views.toggle_post_dislike, name='post_dislike_toggle'),
    path('post/<int:pk>/comment_like/<int:comment_pk>/', views.toggle_comment_like, name='comment_like_toggle'),
    path('post/<int:pk>/comment_dislike/<int:comment_pk>/', views.toggle_comment_dislike, name='comment_dislike_toggle')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include("blog.urls", namespace='blog')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('rick-and-morty/', include("rick_and_morty.urls", namespace='rick_and_morty')),
    path('weather/', include("weather.urls", namespace='weather')),
    path('api/1.0/', include("api.urls", namespace='api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.db import models

from django_extensions.db.models import AutoSlugField

from blog.validators import validate_title

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, validators=[validate_title])
    slug = AutoSlugField(populate_from='title', unique=True)
    body = models.TextField()
    image = models.ImageField(upload_to="img/%Y/%m/%d/")
    rating = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='posts')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('rating', '-create_at', '-update_at')

    def __str__(self):
        return self.title

    def is_liked_by(self, user) -> bool:
        return PostLike.objects.filter(post=self, user=user).exists()

    def is_disliked_by(self, user) -> bool:
        return PostDislike.objects.filter(post=self, user=user).exists()

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CharField,
                               related_name='comments')
    body = models.CharField(max_length=255)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-update_at', '-create_at')
        indexes = [
            models.Index(fields=['-update_at', '-create_at']),
        ]

    def __str__(self):
        return f'{self.author} - {self.post.title}'

    def is_liked_by(self, user) -> bool:
        return CommentLike.objects.filter(comment=self, user=user).exists()

    def is_disliked_by(self, user) -> bool:
        return CommentDislike.objects.filter(comment=self, user=user).exists()


class PostLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post_likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes")
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["user", "post"]

    def __str__(self):
        return f'{self.user} - {self.post}'


class PostDislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post_dislikes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="dislikes")
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["user", "post"]

    def __str__(self):
        return f'{self.user} - {self.post}'


class CommentLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment_likes")
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="likes")
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["user", "comment"]

    def __str__(self):
        return f'{self.user} - {self.comment}'


class CommentDislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment_dislikes")
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="dislikes")
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["user", "comment"]

    def __str__(self):
        return f'{self.user} - {self.comment}'

blog/forms.py
from django import forms
from django.core.validators import FileExtensionValidator

from blog.models import Comment, Post
from blog.validators import validate_file_size


class PostForm(forms.ModelForm):
    image = forms.ImageField(validators=[
        validate_file_size,
        FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])
    ])

    class Meta:
        model = Post
        fields = ['title', 'body', 'image', 'category']


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView

from .models import Post, Comment, PostLike, PostDislike, CommentDislike, CommentLike, Category
from .forms import CommentForm, PostForm
from .utils import paginate_queryset, get_request_params

User = get_user_model()


class PostListView(ListView):
    model = Post
    template_name = 'blog/post/list.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        queryset = super().get_queryset()
        categories = self.request.GET.getlist('categories')
        date_end = self.request.GET.get('date_end', None)
        user = self.request.GET.get('user', None)
        order = self.request.GET.get('order', None)

        if user:
            queryset = queryset.filter(author__username=user)

        if categories:
            queryset = queryset.filter(category__name__in=categories)

        if date_end:
            queryset = queryset.filter(update_at__gte=date_end)

        keyword = self.request.GET.get('keyword', )
        if keyword:
            queryset = queryset.filter(title__icontains=keyword)

        if order == 'rating':
            queryset = queryset.order_by('rating')

        if order == 'update':
            queryset = queryset.order_by('-update_at')

        if order == 'create':
            queryset = queryset.order_by('-create_at')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        per_page = self.request.GET.get('per_page', self.paginate_by)
        paginator = Paginator(context['posts'], per_page)
        page = self.request.GET.get('page', 1)
        posts = paginator.get_page(page)
        query_string = self.request.GET.urlencode()

        context.update({
            'title': 'Home page',
            'posts': posts,
            'total_pages': paginator.num_pages,
            'query_string': query_string,

        })

        return context


class PostSearchView(PostListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get_context('search', )

        if search_query:
            queryset = queryset.filter(Q(title__icontains=search_query) | Q(body__icontains=search_query))

        return queryset


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    context = {
        'post': post,
        'form': CommentForm(),
    }
    return render(request, 'blog/post/detail.html', context)


@login_required
def form_edit_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.user != post.author:
        raise PermissionDenied("You are not a post author")

    form = PostForm(instance=post)
    return render(request, 'blog/post/edit_post.html', {'form': form, 'post': post})


@require_http_methods(["POST"])
@login_required
def edit_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.user != post.author:
        raise PermissionDenied("You are not a post author")

    form = PostForm(request.POST, request.FILES, instance=post)
    if form.is_valid():
        form.save()
        return redirect('blog:post_detail', slug=post.slug)
    return render(request, 'blog/post/edit_post.html', {'form': form, 'post': post})


@login_required
def from_post(request):
    return render(request, 'blog/post/form_post.html', {'form': PostForm()})


@require_http_methods(["POST"])
@login_required
def add_post(request):
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('blog:home')

    context = {
        'form': form,
    }
    return render(request, 'blog/post/form_post.html', context)


@require_http_methods(["POST"])
@login_required
def add_post_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        post.rating += 3
        post.save()
        comment.save()
        return redirect('blog:post_detail', slug=post.slug)
    else:
        context = {
            'post': post,
            'form': form,
        }
        return render(request, 'blog/post/detail.html', context)


@login_required
def toggle_post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post_like, created = PostLike.objects.get_or_create(
        user=request.user,
        post=post,
    )
    if not created:
        post_like.delete()
        post.rating -= 2
        post.save()
    else:
        post.rating += 2
        if post.is_disliked_by(request.user):
            post.rating += 2
            post_dislike = PostDislike.objects.get(post=post, user=request.user)
            post_dislike.delete()
        post.save()
    return redirect('blog:post_detail', slug=post.slug)


@login_required
def toggle_post_dislike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post_dislike, created = PostDislike.objects.get_or_create(
        user=request.user,
        post=post,
    )
    if not created:
        post.rating += 2
        post_dislike.delete()
        post.save()
    else:
        post.rating -= 2
        if post.is_liked_by(request.user):
            post.rating -= 2
            post_like = PostLike.objects.get(post=post, user=request.user)
            post_like.delete()
            post.save()
    return redirect('blog:post_detail', slug=post.slug)


@login_required
def toggle_comment_like(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    post = comment.post
    comment_like, created = CommentLike.objects.get_or_create(
        user=request.user,
        comment=comment,
    )
    if not created:
        comment_like.delete()
        post.rating -= 1
        post.save()
    else:
        post.rating += 1
        if comment.is_disliked_by(request.user):
            post.rating += 1
            comment_dislike = CommentDislike.objects.get(comment=comment, user=request.user)
            post.save()
            comment_dislike.delete()
    return redirect('blog:post_detail', slug=comment.post.slug)


@login_required
def toggle_comment_dislike(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    post = comment.post
    comment_dislike, created = CommentDislike.objects.get_or_create(
        user=request.user,
        comment=comment,
    )
    if not created:
        post.rating += 1
        comment_dislike.delete()
        post.save()
    else:
        post.rating -= 1
        if comment.is_liked_by(request.user):
            post.rating -= 1
            comment_like = CommentLike.objects.get(comment=comment, user=request.user)
            post.save()
            comment_like.delete()
    return redirect('blog:post_detail', slug=comment.post.slug)


# def search_posts(request):
#     if request.method == 'GET':
#         search_query = request.GET.get('search', '')
#         post = Post.objects.filter(title__icontains=search_query)
#         first_post = post.first()
#         if post:
#             return redirect('blog:post_detail', slug=first_post.slug)
#
#     return redirect('blog:home')

templates/blog/post/add_post.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>you really want to add a post</h1>
    <a href="{% url 'blog:home' %} " type="button" class="btn btn-light">Light</a>
    <button type="button" class="btn btn-dark">Dark</button>
{% endblock %}

templates/blog/post/detail.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}
{% load blog_filters %}


{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-10">
        <div class="col-md-8 mx-auto mt-5">
            <h1 class="mb-4">{{ post.title }}</h1>
        </div>
        <div class="text-center">
            <img src="{{ post.image.url }}" alt="" class="img-fluid mx-auto d-block mb-3">
        </div>

        <div class="card mb-4">
            <div class="card-body">
                <p class="card-text">{{ post.body|linebreaks }}</p>
            </div>
            <div class="card-footer text-muted d-flex justify-content-between align-items-center">
                <p class="mb-0">
                    <i class="fas fa-user mx-1"></i>
                    <a class="text-secondary text-decoration-none" href="{% url 'accounts:profile' pk=post.author.pk %}">@{{ post.author }}</a>
                    - {{ post.create_at|date:"D d M Y" }}
                    {% if post.author == request.user %}
                    <a href="{% url 'blog:edit_post' slug=post.slug %} "><i class="fa-solid fa-pen-to-square fa-lg"></i></a>
          {% endif %}
                </p>
                <div class="d-flex align-items-center ml-auto" id="postFooter">
                    <div class="d-flex flex-row align-items-center text-primary">
                        <div class="d-flex align-items-center mb-3 me-4">
                            <a href="{% url 'blog:post_like_toggle' pk=post.pk %}" class="like-button me-1">
                            {% if post|is_liked_by:request.user %}
                                <i class="fas fa-thumbs-up ms-2"></i>
                            {% else %}
                                <i class="far fa-thumbs-up ms-2"></i>
                            {% endif %}
                            </a>
                            <p class="small mb-0" id="likesCount">{{ post.likes.count }}</p>
                        </div>
                        <div class="d-flex align-items-center mb-3">
                            <a href="{% url 'blog:post_dislike_toggle' pk=post.pk %}" class="like-button me-1">
                            {% if post|is_disliked_by:request.user %}
                                <i class="fa-solid fa-thumbs-down ms-2"></i>
                            {% else %}
                                <i class="fa-regular fa-thumbs-down ms-2"></i>
                            {% endif %}
                            </a>
                            <p class="small mb-0" id="dislikesCount">{{ post.dislikes.count }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<hr class="col-lg-10"/>

<section>
    <div class="container my-5 py-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="col-5 mb-4">
                    <form action="{% url 'blog:post_comment_create' post_pk=post.pk %}" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-info">Add</button>
                    </form>
                </div>

                <div class="card text-dark">
                    <div class="card-body p-4">
                        <h4 class="mb-0">Recent comments</h4>
                        <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>
                        {% for comment in post.comments.all %}
                        <h6 class="fw-bold mb-1">{{ comment.author }}</h6>
                        <div class="d-flex align-items-center mb-3">
                            <p class="mb-0">
                                {{ comment.create_at|date:"D d M Y" }}
                                <span class="badge bg-primary">Pending</span>
                            </p>
                            <a href="#!" class="link-muted"><i class="fas fa-pencil-alt ms-2"></i></a>
                            <a href="#!" class="link-muted"><i class="fas fa-redo-alt ms-2"></i></a>
                            <a href="#!" class="link-muted comment-like-button"></a>
                            <a href="{% url 'blog:comment_like_toggle' pk=post.pk comment_pk=comment.pk %}" class="like-button me-1">
                            {% if comment|is_liked_by:request.user %}
                                <i class="fas fa-thumbs-up ms-2"></i>
                            {% else %}
                                <i class="far fa-thumbs-up ms-2"></i>
                            {% endif %}
                            </a>
                            <p class="small mb-0" id="likesCount">{{ comment.likes.count }}</p>

                            <a href="{% url 'blog:comment_dislike_toggle' pk=post.pk comment_pk=comment.pk %}" class="like-button me-1">
                            {% if comment|is_disliked_by:request.user %}
                                <i class="fa-solid fa-thumbs-down ms-2"></i>
                            {% else %}
                                <i class="fa-regular fa-thumbs-down ms-2"></i>
                            {% endif %}
                            </a>
                            <p class="small mb-0" id="likesCount">{{ comment.dislikes.count }}</p>
                        </div>
                        <p class="mb-0">
                            {{ comment.body }}
                        </p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

</div>
{% endblock %}

templates/blog/post/edit_post.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}



{% block content %}
    <form action="{% url 'blog:toggle_edit_post' slug=post.slug %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info">Save</button>
    </form>
{% endblock %}

templates/blog/post/form_crispy.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}


{% block title %}
  Send data to server
{% endblock title %}


{% block content %}
  <h1>Form</h1>
  <div class="col-6">
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-info">Add</button>
    </form>
  </div>
{% endblock content %}

templates/blog/post/form_post.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Form</h1>
  <div class="col-6">
    <form action="{% url 'blog:add_post' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-info">Add</button>
    </form>
  </div>
{% endblock content %}

templates/blog/post/form_raw.html
{% extends 'base/_base.html' %}

{% block title %}
  Send data to server
{% endblock title %}


{% block content %}
  <h1>Form</h1>
  <div class="col-6">
    {% if error %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
    {% endif %}

    <form action="" method="post">
      {% csrf_token %}
      <label for="comment__input-one">Comment one</label>
      <input type="text"
             class="form-control mt-2 mb-3"
             id="comment__input-one"
             name="comment"
             required>

      <label for="comment__input-two">Comment second</label>
      <input type="text"
             class="form-control mt-2 mb-3"
             id="comment__input-two"
             name="comment">

      <button type="submit" class="btn btn-info">Add</button>
    </form>
  </div>
{% endblock content %}

templates/blog/post/list.html
{% extends 'base/_base.html' %}

{% block content %}
    <a href="{% url 'blog:from_post' %}"><i class="fa-solid fa-square-plus fa-xl"></i></a>
{% include 'base/_pagination.html' with items=posts %}
<!-- Example single danger button -->

<div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Order
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'blog:home' %}?order=rating">Rating</a></li>
    <li><a class="dropdown-item" href="{% url 'blog:home' %}?order=update">Update</a></li>
    <li><a class="dropdown-item" href="{% url 'blog:home' %}?order=create">Create</a></li>
  </ul>
</div>

<div class="row mb-2">
  {% for post in posts %}

  <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-2 text-primary">{{ post.category }}</strong>
        <h3 class="mb-0">{{ post.title }}</h3>
        <div class="mb-1 text-muted">{{ post.create_at|timesince }}</div>
        <p class="card-text mb-auto">{{ post.body|truncatewords:15 }}</p>
        <a href="{{ post.get_absolute_url }}" class="stretched-link">Continue reading</a>
      </div>
      <div class="col-auto d-none d-lg-block mt-4">
        <img src="{{ post.image.url }}" alt="" width="300">
        <p><strong>@{{ post.author }}</strong></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>



{% endblock %}