api/urls.py
from django.urls import path

from api import views

app_name = 'api'


urlpatterns = [
    path('movies/genres/', views.GenresListAPIView.as_view(), name='genres_list'),
    path('movies/genres/<int:pk>/', views.GenresDetailAPIView.as_view(), name='genres_detail'),
    path('movies/movies/', views.MoviesListAPIView.as_view(), name='movies_list'),
    path('movies/movies/<int:pk>/', views.MovieDetailAPIView.as_view(), name='movies_detail'),
    #
    # path('posts/posts', views.PostListAPIView.as_view(), name='post_list'),
    # path('posts/posts/<int:pk>/', views.PostDetailAPIView.as_view(), name='post_detail'),
    path('posts/category', views.CategoryListAPIView.as_view(), name='category_list'),
    path('posts/category/<int:pk>/', views.CategoryDetailAPIView.as_view(), name='category_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include("blog.urls", namespace='blog')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('rick-and-morty/', include("rick_and_morty.urls", namespace='rick_and_morty')),
    path('weather/', include("weather.urls", namespace='weather')),
    path('api/1.0/', include("api.urls", namespace='api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/urls.py
from django.urls import path

from .views import widget, CatalogView, AddView, delete, forecast

app_name = 'weather'

urlpatterns = [
    path('widget/', widget, name='widget'),
    path('forecast/', forecast, name='forecast'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('add/', AddView.as_view(), name='add'),
    path('delete/<slug:slug>', delete, name='delete')
    # path('add/toggle/', toggle_add_city, name="toggle_add"),
]

weather/models.py
from django.db import models

from accounts.models import CustomUser
from weather.validators import validate_city


class City(models.Model):
    city = models.CharField(max_length=100, validators=[validate_city])
    info = models.TextField()
    lon = models.FloatField(blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "cities"

    def __str__(self):
        return self.city


class Weather(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    user = models.ManyToManyField(CustomUser,
                                  related_name='weather')

    def __str__(self):
        return f'{self.user} - {self.city}'

weather/forms.py
from django import forms

from weather.models import Weather, City


class AddForm(forms.ModelForm):
    city = forms.CharField(max_length=100, label='City')  # Use ModelChoiceField for cities.

    class Meta:
        model = City
        fields = ['city']

weather/views.py
import os

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, FormView

from weather.exceptions import CityNotFoundError, ExternalServiceError
from weather.forms import AddForm
from weather.models import Weather, City
from weather.services import CurrentWeatherService, wikipedia_service, ForecastWeatherService

User = get_user_model()


def widget(request):
    city = request.GET.get('city')
    if city is None:
        pass
    api_key = os.getenv('API_TOKEN')
    weather_dto = None
    error = None

    weather_service = CurrentWeatherService(api_key=api_key, units='metric')
    try:
        weather_dto = weather_service.get_weather(city_name=city)
    except CityNotFoundError as exception:
        error = str(exception)
    except ExternalServiceError as exception:
        error = 'External service error, please try again later'

    try:
        city_object = City.objects.get(city=city)
        info = city_object.info
    except City.DoesNotExist:
        info = None
    context = {
        'weather': weather_dto,
        'city_info': info,
        'error': error
    }
    return render(request, 'weather/weather.html', context)


def forecast(request):
    city = request.GET.get('city')
    if city is None:
        pass

    api_key = os.getenv('API_FORECAST_TOKEN')
    forecast_dto = None
    error = None

    forecast_service = ForecastWeatherService(api_key=api_key, units='metric')


    try:
        city_object = City.objects.filter(city=city).first()
        if city_object:
            forecast_dto = forecast_service.get_weather(lon=city_object.lon, lat=city_object.lat)
            name = city_object.city
        else:
            error = 'to find out the weather, add it to your catalog'
    except CityNotFoundError as exception:
        error = str(exception)
    except ExternalServiceError as exception:
        error = 'External service error, please try again later'

    today = forecast_dto.days[0].temp
    tomorrow = forecast_dto.days[1].temp
    after_tomorrow = forecast_dto.days[2].temp

    context = {
        'weather': forecast_dto,
        'city_info': city_object.info,
        'name': name,
        'today': today,
        'tomorrow': tomorrow,
        'after_tomorrow': after_tomorrow,
        'error': error
    }
    return render(request, 'weather/forecast.html', context)


class CatalogView(LoginRequiredMixin, TemplateView):
    template_name = 'weather/catalog.html'

    def get_context_data(self, **kwargs):
        user = User.objects.get(username=self.request.user)
        context = {
            'cities': user.weather.all(),
        }
        return context


# @login_required
# def toggle_add_city(request):
#     city, created = Weather.objects.get_or_create(
#         user=request.user,
#         city=request.f
#     )
#
#     return redirect(f'weather:widget?{city}')


# class AddView(TemplateView):
#     template_name = 'weather/add.html'
#
#     def get_context_data(self, **kwargs):
#         context = {
#             'form': AddForm
#         }
#         return context


class AddView(FormView):
    template_name = 'weather/add.html'
    form_class = AddForm
    success_url = reverse_lazy('weather:catalog')

    def form_valid(self, form):
        catalog = form.save(commit=False)
        api_key = os.getenv('API_TOKEN')

        if not City.objects.filter(city=catalog.city):
            weather_service = CurrentWeatherService(api_key=api_key, units='metric')
            location_dto = weather_service.get_location(city_name=catalog.city)
            catalog.info = wikipedia_service(catalog.city)
            catalog.lon = location_dto.lon
            catalog.lat = location_dto.lat
            catalog.save()

        city = City.objects.filter(city=catalog.city).first()
        if city:
            weather, created = Weather.objects.get_or_create(city=city)
            weather.user.add(self.request.user)
        return super().form_valid(form)


def delete(request, slug):
    city = get_object_or_404(City, city=slug)
    city = Weather.objects.filter(user=request.user, city=city)
    city.delete()
    return redirect('weather:catalog')

# class WidgetView(View):
#
#     def get_context_data(self, **kwargs):
#         country = self.request.GET.get('country', '')
#         weather, temp, name = get_weather(country)
#         context = {
#             'weather': weather,
#             'temp': temp,
#             'name': name
#         }
#
#         return render(self.request, 'weather/weather.html', context)

templates/weather/add.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-info mt-3">Add</button>
</form>
{% endblock %}

templates/weather/catalog.html
{% extends 'base/_base.html' %}

{% block content %}
    <div class="container">

         <div class="row">
    <div class="col">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">City</th>
      <th scope="col">current weather</th>
      <th scope="col">7-day forecast</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for city in cities %}
    <tr>
      <td><p>{{ city.city.city }}</p></td>
      <td><a href="{% url 'weather:widget' %}?city={{ city.city.city }}" class="text-decoration-none">current weather</a></td>
      <td><a href="{% url 'weather:forecast' %}?city={{ city.city.city }}" class="text-decoration-none">7-day forecast</a></td>
      <td><a href="{% url 'weather:delete' slug=city.city.city %}" class="text-decoration-none">Delete</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>

    </div>
  </div>



</div>
<div class="text-center">
<a href="{% url 'weather:add' %}" class="btn btn-info mt-3">Add</a>
</div>
{% endblock %}

templates/weather/forecast.html
{% extends 'base/_base.html' %}


{% block content %}
<section class="vh-100">
  <div class="container py-5">

    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-7 col-xl-5">

        <div id="wrapper-bg"
             class="card text-white bg-image shadow-4-strong"
             style="background: url('{{ weather.gif }}') no-repeat;
                     background-size: 100%;">
          <!-- Main current data -->
          <div class="card-header p-4 border-0">
            <div class="text-center mb-3">
              <p class="h2 mb-1" id="wrapper-name">{{ name }}</p>
              <p class="mb-1" id="wrapper-description">{{ weather.description }}</p>
              <p class="display-1 mb-1" id="wrapper-temp">{{ weather.temp }}°C</p>
              <span class="">Pressure: <span id="wrapper-pressure">{{ weather.pressure }}</span></span>
              <span class="mx-2">|</span>
              <span class="">Humidity: <span id="wrapper-humidity">{{ weather.humidity }}°C</span></span>
            </div>
          </div>

          <!-- Hourly forecast -->
          <div class="card-body p-4 border-top border-bottom mb-2">
            <div class="row text-center">
              {% for hour in weather.hours %}
              <div class="col-2">
                <strong class="d-block mb-2" id="wrapper-time1">{{ hour.hour }}</strong>
                <img id="wrapper-icon-hour1" src="" class="" alt="" />
                <strong class="d-block" id="wrapper-hour1">{{ hour.temp }}</strong>
              </div>
              {% endfor %}

            </div>
          </div>

          <!-- Daily forecast -->

            <div class="card-body px-5">
            <div class="row align-items-center">
              <div class="col-lg-6">
                <strong>Today</strong>
              </div>

              <div class="col-lg-2 text-center">
                <img id="wrapper-icon-today" src="" class="w-100" alt="" />
              </div>

              <div class="col-lg-4 text-end">
                <span id="wrapper-forecast-temp-today">{{ today }}</span>
              </div>
            </div>



            <div class="row align-items-center">
              <div class="col-lg-6">
                <strong>Tomorrow</strong>
              </div>

              <div class="col-lg-2 text-center">
                <img id="wrapper-icon-tomorrow" src="" class="w-100" alt="" />
              </div>

              <div class="col-lg-4 text-end">
                <span id="wrapper-forecast-temp-tomorrow">{{ tomorrow }}</span>
              </div>
            </div>

            <div class="row align-items-center">
              <div class="col-lg-6">
                <strong>Day after tomorrow</strong>
              </div>

              <div class="col-lg-2 text-center">
                <img id="wrapper-icon-dAT" src="" class="w-100" alt="" />
              </div>

              <div class="col-lg-4 text-end">
                <span id="wrapper-forecast-temp-dAT">{{ after_tomorrow }}</span>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>
    {{ city_info|safe }}
{% endblock %}

templates/weather/weather.html
{% extends 'base/_base.html' %}

{% block content %}
  {% if error %}
    <div>
      <h1>{{ error }}</h1>
    </div>
  {% else %}
    <section class="vh-100" style="background-color: #4B515D;">
      <div class="container py-5 h-100">

        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-8 col-lg-6 col-xl-4">

            <div class="card" style="color: #4B515D; border-radius: 35px;">
              <div class="card-body p-4">

                <div class="d-flex">
                  <h6 class="flex-grow-1">{{ weather.name }}</h6>
                  <h6>{{ weather.last_update }}</h6>
                </div>

                <div class="d-flex flex-column text-center mt-5 mb-4">
                  <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"> {{ weather.temp }}°C </h6>
                  <span class="small" style="color: #868B94">{{ weather.description }}</span>
                </div>

                <div class="d-flex align-items-center">
                  <div class="flex-grow-1" style="font-size: 1rem;">
                    <div><i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1"> {{ weather.wind }} km/h
                      </span></div>
                    <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1"> {{ weather.humidity }}% </span>
                    </div>
                    <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"> {{ weather.sunset }}h </span>
                    </div>
                  </div>
                  <div>
                      <img src={{ weather.icon }} width="100px">
                  </div>
                </div>

              </div>

            </div>

          </div>
        </div>

      </div>
    </section>
      {% if city_info %}
        <p>{{ city_info|safe }}</p>
      {% endif %}
  {% endif %}
{% endblock %}